import type { NextPage } from 'next';
import Head from 'next/head';
import { signIn, signOut, useSession } from "next-auth/client";
import { Button, CircularProgress } from '@material-ui/core';
import { PrismaClient } from '@prisma/client';
import Image from 'next/image';
import eximg from '../public/fakeimg-2.webp';

const Home: NextPage = () => {
  const [ session, loading ] = useSession();

  if(loading) {
    return <span className="text-center"><CircularProgress /></span>
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {!session && (
          <>
            サインインしてください。 <br />
            <Button variant="outlined" onClick={() => signIn('google')}>Googleでサインイン</Button>
          </>
        )}
        {session && (
          <>
            サインイン完了。 {session.user?.name} <br />
            <img src={session.user?.image?.toString()} />
            <Button variant="outlined" onClick={() => signOut()}>Sign out</Button>
          </>
        )}
      </div>
      <Image src={eximg} />
    </div>
  )
}

export default Home

declare global {
  var prisma: PrismaClient;
}