import { PrismaClient } from '@prisma/client';
import type { NextPage } from 'next';
import Head from 'next/head';
import { signIn, signOut, useSession } from "next-auth/client";
import { Button } from '@material-ui/core';

const Home: NextPage = () => {
  const [ session, loading ] = useSession();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {!session && (
          <>
            サインインしてください。 <br />
            <Button variant="outlined" onClick={signIn}>Sign in</Button>
          </>
        )}
        {session && (
          <>
            サインイン完了。 email: {session.user?.email} <br />
            <Button variant="outlined" onClick={signOut}>Sign out</Button>
          </>
        )}
      </div>
    </div>
  )
}

export default Home

declare global {
  var prisma: PrismaClient;
}